# Generated by Django 4.1 on 2022-09-04 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_tags_alter_productpackage_price_and_more'),
        ('orders', '0002_order_payment_type_order_sessionid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_type',
            new_name='paymentType',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sessionId',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productpackage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trackingNumber',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
