# Generated by Django 4.0.8 on 2022-10-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('usps', 'USPS'), ('ups', 'UPS'), ('fedex', 'FEDEX')], max_length=20, null=True),
        ),
    ]
