# Generated by Django 4.0.8 on 2022-10-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_shipping_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentType',
            new_name='payment_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='trackingNumber',
            new_name='tracking_number',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
