# Generated by Django 4.1 on 2022-08-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesTags', '0002_thirdsubcategory_remove_subcategories_product_and_more'),
        ('products', '0002_product_category_product_subcategory_product_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='categoriesTags.tag'),
        ),
    ]
