# Generated by Django 4.1 on 2022-09-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesTags', '0002_thirdsubcategory_remove_subcategories_product_and_more'),
        ('products', '0003_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='categoriesTags.tag'),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
