# Generated by Django 4.1.1 on 2022-09-12 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_featuredproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredproduct',
            old_name='rank',
            new_name='slot',
        ),
    ]
