# Generated by Django 4.1.1 on 2022-10-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesTags', '0003_category_hassubcategory_subcategory_category'),
        ('products', '0008_productpackage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagslist', to='categoriesTags.tag'),
        ),
    ]
