# Generated by Django 4.0.8 on 2022-10-18 17:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='care',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
