# Generated by Django 4.1 on 2022-08-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesTags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='subCategory',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='t',
            new_name='body',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='SubCategories',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
    ]
