# Generated by Django 4.1.1 on 2022-10-04 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesTags', '0002_thirdsubcategory_remove_subcategories_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hasSubcategory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoriesTags.category'),
        ),
    ]
