# Generated by Django 4.1.2 on 2022-10-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesTags', '0003_category_hassubcategory_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='placeholder',
            field=models.ImageField(blank=True, null=True, upload_to='placeholders/'),
        ),
    ]
