# Generated by Django 4.1.2 on 2022-10-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesTags', '0004_subcategory_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hasSubcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='placeholder',
            field=models.ImageField(blank=True, null=True, upload_to='placeholders/'),
        ),
    ]
