# Generated by Django 4.1.1 on 2022-09-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='static/products/media/'),
        ),
    ]
