# Generated by Django 4.1.1 on 2022-09-17 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_scientific_name'),
        ('media', '0002_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
